name: 'Pacttest uploader'
description: 'This is a pacttest uploader'
inputs: 
  DOCKER_IMAGE_URL:
    description: 'Full URL for docker image'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Run the image, and copy the json files locally
      run: ls
