name: 'Pacttest uploader'
description: 'This is a pacttest uploader'
inputs:
    DOCKER_IMAGE_URL:
        description: 'Full URL for docker image'
        required: true

runs:
    using: 'composite'
    steps:
    - name: Setup docker container
      run: |
        docker pull ${{ inputs.DOCKER_IMAGE_URL }}
        container_id=`docker run -d --entrypoint tail ${{ inputs.DOCKER_IMAGE_URL }} -f /dev/null`
        if [ $? = "0" ]; then
            mkdir -p files
            docker cp $container_id:/app/pacts files
            docker rm $container_id -f
            ls -alhR files
        else
            echo 'Unable to run the image - ${{ inputs.DOCKER_IMAGE_URL }}'
            exit 1
        fi

        python - <<EOF
        import glob, os, json, urllib.request
        version = ${{ github.run_id }}
        os.chdir('files')
        for f in glob.glob('*.json'):
            with open(f) as json_data:
                pact = json.load(json_data)
                pact_url = 'http://pact-broker.stg.commercial.csnglobal.net/pacts/provider/{}/consumer/{}/version/{}'.format(pact['provider']['name'],pact['consumer']['name'], 1)
                print(pact)
        EOF
        
      shell: sh
