name: 'Pacttest uploader'
description: 'This is a pacttest uploader'
inputs:
    DOCKER_IMAGE_URL:
        description: 'Full URL for docker image'
        required: true

runs:
    using: 'composite'
    steps:
    - name: Setup docker container
      run: |
        curl -fsSL https://get.docker.com/rootless | sh
        export PATH="/home/$USER/bin:$PATH"
        
        container_id=`docker run -d ${{ inputs.DOCKER_IMAGE_URL }}`
        if [$?=0]; then
            mkdir -p files
            docker cp $container_id:/app/pacts files
            docker rm $container_id -f
            ls -alhR files
        else
            echo 'Unable to run the image - ${{ inputs.DOCKER_IMAGE_URL }}'
            exit 1
        fi

        PYTHON_SCRIPT=$(cat <<EOF
        import glob, os, json, urllib.request
        version = ${{ github.run_id }}
        os.chdir('files')
        for f in glob.glob('*.json'):
            with open(f) as json_data:
                pact = json.load(json_data)
                pact_url = 'http://pact-broker.stg.commercial.csnglobal.net/pacts/provider/{}/consumer/{}/version/{}'.format(pact['provider']['name'],pact['consumer']['name'], 1)
                print(pact)
        EOF
        )

        python -c $PYTHON_SCRIPT
      shell: sh
