name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: 
    workflow_dispatch:
jobs:
    build-docker-image:
        name: Build and push docker image
        runs-on: ubuntu-latest
        outputs:
            published_image_path: ${{ steps.build-image.outputs.image-id }}
        steps:
        - name: Code checkout
          uses: actions/checkout@v3

        - name: Build image
          id: build-image
          run: |
            #echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u kishanhathiwala --password-stdin
            #docker build -f Dockerfile --tag ghcr.io/kishanhathiwala/webapplication2:latest .
            #docker push ghcr.io/kishanhathiwala/webapplication2:latest
            #echo "image-id=ghcr.io/kishanhathiwala/webapplication2:latest" >> $GITHUB_OUTPUT
            
            docker build -f Dockerfile --tag ttl.sh/webapplication2:24h .
            docker push ttl.sh/webapplication2:24h
            echo "image-id=ttl.sh/webapplication2:24h" >> $GITHUB_OUTPUT

    pacttest-uploader:
        runs-on: ubuntu-latest
        needs: [build-docker-image]
        steps:
        - name: Prepare python
          uses: actions/setup-python@v4.5.0
         
        - name: Code checkout
          uses: actions/checkout@v3

        - name: Login to github registry
          run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u kishanhathiwala --password-stdin

        - name: Setup docker container
          uses: ./.github/actions/pacttest-uploader
          with:
            DOCKER_IMAGE_URL: ${{ needs.build-docker-image.outputs.published_image_path }}
