name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: [push]
jobs:
    build-docker-image:
        name: Build and push docker image
        runs-on: ubuntu-latest
        outputs:
            published_image_path: ${{ steps.build-image.outputs.image-id }}
        steps:
        - name: Code checkout
          uses: actions/checkout@v3

        - name: Build image
          id: build-image
          run: |
            docker build -f Dockerfile --tag ttl.sh/webapplication2:2h .
            docker push ttl.sh/webapplication2:2h
            echo "image-id=ttl.sh/webapplication2:2h" >> $GITHUB_OUTPUT

    pacttest-uploader:
        runs-on: ubuntu-latest
        needs: [build-docker-image]
        steps:
        - name: Prepare python
          uses: actions/setup-python@v4.5.0
          with:
            python-version: 3.11.0
          
        - name: Setup docker container
          uses: kishanhathiwala/WebApplication2/.github/actions/pacttest-uploader@latest
          with:
            DOCKER_IMAGE_URL: ${{ needs.build-docker-image.outputs.published_image_path }}
