name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - Production AU
          - Production LATAM
          - ALL Production
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11.0
      
      - name: Prepare python script
        id: python-script
        run: |
          PYTHON_SCRIPT=$(cat <<EOF
          import json, urllib.request
          with open('/mnt/c/Kishan/repos/csn.showroom.cms.api/ConsumerPact.Tests/bin/Debug/pacts/Csn.Showroom.CMS.Api-Csn.Showroom.Spec.Api.json') as json_data:
              pact = json.load(json_data)
              pact_url = 'http://pact-broker.stg.commercial.csnglobal.net/pacts/provider/{}/consumer/{}/version/{}'.format(pact['provider']['name'],pact['consumer']['name'], 1)
              opener = urllib.request.build_opener(urllib.request.HTTPHandler)
              request = urllib.request.Request(pact_url, data=json.dumps(pact).encode('utf-8'))
              request.add_header('Content-Type', 'application/json')
              request.add_header('Authorization','Basic dXfltyFMgNOFZAxr8io9wJ37iUpY42M:O5AIZWxelWbLvqMd8PkAVycBJh2Psyg1')
              request.get_method = lambda: 'PUT'
              print(pact_url)
              url = opener.open(request, timeout = 10)
              response = url.read()
              print(response)
          EOF
          )
          echo "text<<EOF" >> $GITHUB_OUTPUT
          echo "pythonScript=$PYTHON_SCRIPT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Execute python script
        run: |
          python -c "${{ steps.python-script.outputs.pythonScript }}"
  
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - run: npm -v
