name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - Production AU
          - Production LATAM
          - ALL Production
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - run: npm -v
